dist: xenial

addons:
  apt:
    packages:
      - ant-optional

language: php

php:
  - "7.4"
  - "7.3"
  - "7.2"
  - "7.1"
  - "nightly"

env:
  - "CONTAO_VERSION=contao/core-bundle ~4.4.0"
  - "CONTAO_VERSION=contao/core-bundle ~4.9.0"
  - "CONTAO_VERSION=contao/core-bundle ~4.10.0"

matrix:
  allow_failures:
    - php: "nightly"

before_script:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer self-update --1 && composer --version
  - travis_retry composer require $CONTAO_VERSION --no-update
  - travis_retry composer update --prefer-dist --no-interaction
  - travis_retry composer global require maglnet/composer-require-checker ^2.0

script: ant -keep-going

git:
  depth: 2147483647

cache:
  directories:
    - vendor
