services:
  netzmacht.contao_form.form_type.form_generator:
    class: Netzmacht\ContaoFormBundle\Form\FormGeneratorType
    arguments:
      - '@netzmacht.contao_toolkit.repository_manager'
      - '@netzmacht.contao_form.form_generator.type_builder'
    tags:
      - { name: form.type }

  netzmacht.contao_form.form_generator.type_builder:
    class: Netzmacht\ContaoFormBundle\Form\FormGenerator\FieldTypeBuilder
    arguments:
      - []

  netzmacht.contao_form.form_generator.mapper.checkbox:
    class: Netzmacht\ContaoFormBundle\Form\FormGenerator\Mapper\CheckboxFieldMapper
    tags:
      - { name: netzmacht.contao_form.form_generator.mapper }

  netzmacht.contao_form.form_generator.mapper.fieldset:
    class: Netzmacht\ContaoFormBundle\Form\FormGenerator\Mapper\FieldsetFieldMapper
    tags:
      - { name: netzmacht.contao_form.form_generator.mapper }

  netzmacht.contao_form.form_generator.mapper.hidden:
     class: Netzmacht\ContaoFormBundle\Form\FormGenerator\Mapper\HiddenFieldMapper
     tags:
      - { name: netzmacht.contao_form.form_generator.mapper }

  netzmacht.contao_form.form_generator.mapper.password:
    class: Netzmacht\ContaoFormBundle\Form\FormGenerator\Mapper\PasswordFieldMapper
    tags:
      - { name: netzmacht.contao_form.form_generator.mapper }

  netzmacht.contao_form.form_generator.mapper.radio:
    class: Netzmacht\ContaoFormBundle\Form\FormGenerator\Mapper\RadioFieldMapper
    tags:
      - { name: netzmacht.contao_form.form_generator.mapper }

  netzmacht.contao_form.form_generator.mapper.select:
    class: Netzmacht\ContaoFormBundle\Form\FormGenerator\Mapper\SelectFieldMapper
    tags:
      - { name: netzmacht.contao_form.form_generator.mapper }

  netzmacht.contao_form.form_generator.mapper.submit:
    class: Netzmacht\ContaoFormBundle\Form\FormGenerator\Mapper\SubmitFieldMapper
    tags:
      - { name: netzmacht.contao_form.form_generator.mapper }

  netzmacht.contao_form.form_generator.mapper.textarea:
    class: Netzmacht\ContaoFormBundle\Form\FormGenerator\Mapper\TextareaFieldMapper
    tags:
      - { name: netzmacht.contao_form.form_generator.mapper }

  netzmacht.contao_form.form_generator.mapper.text:
    class: Netzmacht\ContaoFormBundle\Form\FormGenerator\Mapper\TextFieldMapper
    tags:
      - { name: netzmacht.contao_form.form_generator.mapper }
